In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [19]:
# Pull data: Year, player name, position, points, # of Games
col_list = ["Year", "Player", "Rounded Position", "WS"]
df = pd.read_csv("Resources/NBA_Season_Data_dataworld.csv", usecols=col_list)
df_cleaned = df.drop(df[df['Year'] == 2016].index)
df_cleaned["Rounded Position"] = df_cleaned["Rounded Position"].replace([1.0,2.0,3.0,4.0,5.0],["Point guard","Shooting guard","Small forward","Power Forward","Center"])


df_cleaned

       Year            Player    WS Rounded Position
0      1978    Truck Robinson   6.5    Power Forward
1      1978       Randy Smith   7.9      Point guard
2      1978       Elvin Hayes   8.3    Power Forward
3      1978       Dave Cowens  10.8    Power Forward
4      1978        Bob McAdoo  10.9    Power Forward
...     ...               ...   ...              ...
16854  2015  Jerrelle Benimon   0.0           Center
16855  2015       Sim Bhullar   0.0           Center
16856  2015     Eric Moreland   0.0           Center
16857  2015       Malcolm Lee   0.0   Shooting guard
16858  2015      Toure' Murry   0.0   Shooting guard

[16859 rows x 4 columns]

In [20]:
# Groupby dataset by year and position
# get the average of WS of each position in each year
avg_WS_of_each_pos= df_cleaned.groupby(["Year","Rounded Position"]).agg({'WS': ['mean']})
WS_Analysis = avg_WS_of_each_pos.reset_index()
WS_Analysis.columns = WS_Analysis.columns.map('|'.join).str.strip('|')
WS_Analysis

     Year Rounded Position   WS|mean
0    1978           Center  4.930000
1    1978      Point guard  2.290909
2    1978    Power Forward  3.092537
3    1978   Shooting guard  2.893333
4    1978    Small forward  2.353571
..    ...              ...       ...
185  2015           Center  3.159596
186  2015      Point guard  2.160833
187  2015    Power Forward  2.164463
188  2015   Shooting guard  1.453043
189  2015    Small forward  2.127500

[190 rows x 3 columns]

In [ ]:
WS_Analysis.to_csv("WS_avg.csv")