In [12]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [13]:
# Pull data: Year, player name, position, points, # of Games
col_list = ["Year", "Player", "Rounded Position", "WS"]
df = pd.read_csv("NBA_Season_Data.csv", usecols=col_list)
df_cleaned = df.drop(df[df['Year'] == 2016].index)
df_cleaned["Rounded Position"] = df_cleaned["Rounded Position"].replace([1.0,2.0,3.0,4.0,5.0],["Point guard","Shooting guard","Small forward","Power Forward","Center"])


df_cleaned

       Year            Player Rounded Position   WS
0      1999  Gheorghe Muresan           Center -0.1
2      1979       Ron Behagen   Shooting guard  0.0
3      2001    Larry Robinson      Point guard  0.0
4      2006      Nene Hilario    Power Forward -0.1
5      1987    Michael Wilson      Point guard -0.1
...     ...               ...              ...  ...
17258  1991      Ian Lockhart    Small forward  0.0
17259  2008      Gerald Green    Power Forward  0.1
17260  2009       Steven Hill           Center  0.0
17261  2005     Jackie Butler    Small forward  0.1
17262  2014   DeAndre Liggins           Center  0.0

[16859 rows x 4 columns]

In [22]:
# Groupby dataset by year and position
# get the average of WS of each position in each year
avg_WS_of_each_pos= df_cleaned.groupby(["Year","Rounded Position"]).agg({'WS': ['mean']})
WS_Analysis = avg_WS_of_each_pos.reset_index()
WS_Analysis.columns = WS_Analysis.columns.map('|'.join).str.strip('|')
WS_Analysis = WS_Analysis.rename(columns={'WS|mean': 'WSmean'})
WS_Analysis

     Year Rounded Position    WSmean
0    1978           Center  4.930000
1    1978      Point guard  2.290909
2    1978    Power Forward  3.092537
3    1978   Shooting guard  2.893333
4    1978    Small forward  2.353571
..    ...              ...       ...
185  2015           Center  3.159596
186  2015      Point guard  2.160833
187  2015    Power Forward  2.164463
188  2015   Shooting guard  1.453043
189  2015    Small forward  2.127500

[190 rows x 3 columns]

In [23]:
WS_Analysis.to_csv("WS_avg.csv")